import { Darker_Grotesque } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";

const darker_grotesque = Darker_Grotesque({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={darker_grotesque.className}>
        <Providers>
          <main className="">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
